### ISSUE TITLE
如何保证judge模块的高可用？

### ISSUE THREAD

**Issue by qlyzpqz** [open-falcon/open-falcon#1]
我看了一下transfer的代码，发现transfer对judge模块的一致性哈希表是不会动态变化的，judge的状态只是内存中缓存的11分钟数据，设计时为什么不考虑让transfer能够做到自动剔除不可用的judge呢？

**Comment by laiwei** [comment]
judge 所在的机器，如果坏掉了，是需要人工介入处理的

所以，这块就没有做transfer对 judge的自动摘除。

后续可以考虑下如何更好的优化
